### ISSUE TITLE
Strava heatmap cannot be shown after latest upgrade (vector map)

### ISSUE THREAD

**Issue by arielki** [IsraelHikingMap/VectorMap#9] opened 2019-05-11 13:42 UTC
Strava heatmap cannot be shown after latest upgrade, even after being logged in to Strava and having the heatmap enabled.
Used the following link as the heatmap layer:
https://heatmap-external-a.strava.com/tiles-auth/ride/bluered/{z}/{x}/{y}.png?v=18&px=256

**Comment by HarelM** [comment] 2019-05-11 16:56
Hi and thanks for taking the time to open this issue.
However, this is not the relevant repository for this issue and this issue is also a duplicate of 
https://github.com/IsraelHikingMap/Site/issues/1020
Please see my comments there and in our facebook group.

**Closed by HarelM** 2019-05-11 16:56 UTC
