### ISSUE TITLE
Show Railway in Construction

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#154] opened 2023-07-16 11:26 UTC
New railways are huge projects that impacts vast open areas. Notably the new eastern line. 
I believe users should be aware of such a large element on the map. Either to avoid it while traveling or to go see what's going on, being careful in construction sites.
Therefore it is suggested to Show Railway in Construction on both cycling and hiking maps.
Thank you!

**Comment by zstadler** [comment] 2023-07-16 12:03
Are you referring to railway lines and/or railway stations? Please add locations of specific examples.
What about the light rail works around Tel-Aviv? It would further clutter this dense urban area.

**Comment by Tsurha** [comment] 2023-07-16 13:26
I'm reffering to heavy rail lines. For example along this path:
https://israelhiking.osm.org.il/share/yK0ABWksmt
I suggest you look at updated aerial photos and see how huge the project is and it's impact on open areas.

**Comment by zstadler** [comment] 2023-07-16 13:47
I understand that you refer to ways tagged with `railway=construction` and `construction=rail` 
[Here](https://overpass-turbo.eu/s/1xrP) are the ways currently defined as such.

**Comment by zstadler** [comment] 2023-07-16 13:55
In #103, only minor and tertiary roads under construction were added to the ilMTB map. Other road types were not added. Maybe because of [the clutter they would have added](https://overpass-turbo.eu/s/1xrR).

@valleyofdawn, I'd appreciate your view on this issue.

By design, the hiking map does not show any "under construction" features, and that would also include railways.

**Comment by zstadler** [comment] 2023-08-19 06:40
It looks like there was a deliberate decision to limit the types of road constructions that would show on the map.

Closing

**Closed by zstadler** 2023-08-19 06:40 UTC
